name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - dask
  - plotly
  - tensorflow=2.0.0
  - scipy
  - xlrd
